CREATE DATABASE csed;
USE csed;

CREATE TABLE account(id INT UNSIGNED AUTO_INCREMENT,
email VARCHAR(50) NOT NULL,
first_name VARCHAR(20) NOT NULL,
last_name VARCHAR(20) NOT NULL,
password VARCHAR(72) NOT NULL,
dob DATE,
created DATETIME,
PRIMARY KEY(id));